/**
 * Reading & categorizing the system clipboard into Ledge's `ItemData`.
 *
 * The clipboard is sampled once into a `ClipSnapshot` (see `./clip`), then
 * classified by the PURE `analyzeSnapshot` / `signatureForSnapshot` functions —
 * which take plain values, so they unit-test without a live clipboard or an
 * Electron mock. The async `captureClipboard` / `clipboardSignature` wrappers
 * just glue the snapshot + per-OS file read to those pure functions.
 *
 * Picking the per-OS file reader is the ONE place the engine keys off
 * `process.platform`; every other branch uses `platform.id`.
 */
import { statSync } from 'node:fs'
import { basename, extname } from 'node:path'
import type {
  FilePayload,
  ImagePayload,
  ItemData,
  LinkPayload,
  TextPayload
} from '../../../../shared/types/clipboard'
import { PREVIEW_LIMIT } from '../../../../shared/types/clipboard'
import { readSnapshot, type ClipSnapshot } from './clip'
import * as win32 from './win32'
import * as darwin from './darwin'
import * as linux from './linux'

/** The file-path reader for the host OS. Selection is by design allowed here. */
const reader = process.platform === 'win32' ? win32 : process.platform === 'darwin' ? darwin : linux

export type { ClipSnapshot } from './clip'

/* ---------------------------------------------------------------- */
/* Detection helpers (pure)                                          */
/* ---------------------------------------------------------------- */

const URL_RE = /^(https?:\/\/|www\.)[^\s]+$/i
const FILE_URL_RE = /file:\/\/\/?([^\s"'<>]+)/i

export type ImageSource = 'screenshot' | 'image'

/** True if the text payload looks like a single URL. */
export function isUrlText(s: string): boolean {
  return URL_RE.test(s.trim())
}

/**
 * Sensitive clipboard formats used by password managers / dictation tools /
 * transient scripts. With the async clipboard we can only see format *names*
 * (not the legacy privacy DWORD values), so we match on the advertised type
 * names case-insensitively — content a tool marked "do not record" must not be
 * captured. (Documented degradation from Edge-Drop's DWORD probes.)
 */
const IGNORED_FORMATS = [
  'ClipboardViewerIgnore',
  'Clipboard Viewer Ignore',
  'ExcludeClipboardContentFromMonitorProcessing',
  'CanIncludeInClipboardHistory',
  'CanUploadToCloudClipboard',
  'org.nspasteboard.ConcealedType',
  'org.nspasteboard.AutoGeneratedType',
  'com.agilebits.onepassword',
  'com.apple.is-sensitive',
  'com.apple.pasteboard.concealed',
  'KeePassClipFormat',
  'com.bitwarden.concealed'
]

export function isExcludedByTypes(types: readonly string[]): boolean {
  const lower = types.map((t) => t.toLowerCase())
  return IGNORED_FORMATS.some((f) => lower.includes(f.toLowerCase()))
}

/** Turn a clipboard `file://` URL into a local path (best-effort, no I/O). */
export function localPathFromClipboardFileUrl(raw: string): string | null {
  const m = raw.match(FILE_URL_RE)
  if (!m) return null
  try {
    let decoded = decodeURIComponent(m[1].replace(/"/g, ''))
    if (/^[a-zA-Z]:[\\/]/.test(decoded) || decoded.startsWith('\\\\')) decoded = decoded.replace(/\//g, '\\')
    return decoded
  } catch {
    return null
  }
}

/**
 * Distinguish an image-intent payload (screenshot, browser "Copy Image",
 * Snipping Tool window capture) from a text-intent one (Excel/Sheets tabular
 * data, rich text, a document, code) when both a bitmap AND text are present.
 */
export function isScreenshotOrImageIntent(hasImage: boolean, rawText: string, rawHtml: string, types: readonly string[] = []): boolean {
  if (!hasImage) return false
  // Checked before the empty-text early return below: some spreadsheet copies
  // (Excel and Google Sheets both, in different ways) land here with an empty
  // text/plain but a fully-formed HTML `<table>` — that must win over the
  // decorative preview bitmap, not fall through to "no text => screenshot".
  if (win32.preferTabularOverImage(types, rawHtml || null)) return false
  if (!rawText) return true
  if (/^<img\b[^>]*>$/i.test(rawText) || /^<img\b[^>]*\/?>$/i.test(rawHtml)) return true
  if (URL_RE.test(rawText) && rawText.length < 500) return true

  if (rawText.includes('\t')) return false
  if (rawText.split(/\r?\n/).map((l) => l.trim()).filter(Boolean).length > 1) return false

  const lowerHtml = rawHtml.toLowerCase()
  if (
    /<(table|tr|td|th|html|body|p|pre|code|ul|ol|li)\b/.test(lowerHtml) ||
    lowerHtml.includes('google-sheets') ||
    lowerHtml.includes('data-sheets') ||
    lowerHtml.includes('urn:schemas-microsoft-com:office:spreadsheet') ||
    lowerHtml.includes('excel')
  ) {
    return false
  }
  if (rawText.length > 200) return false
  return true
}

/** Classify a bitmap capture as a screenshot vs a copied image, from format names + text. */
export function detectClipboardImageSource(types: readonly string[], text: string, html: string): ImageSource {
  const lower = types.map((t) => t.toLowerCase())
  if (lower.some((f) => /screenshot|snipping|screen\s*clip|screenclip/.test(f))) return 'screenshot'
  if (lower.some((f) => /filegroupdescriptor|filecontents|filenamew|shell idlist/.test(f))) return 'image'

  if (localPathFromClipboardFileUrl(html) || localPathFromClipboardFileUrl(text)) return 'image'
  if (/^<img\b/i.test(html.trim()) || URL_RE.test(text.trim())) return 'image'

  const trimmed = text.trim()
  if (
    trimmed &&
    !URL_RE.test(trimmed) &&
    !trimmed.includes('\t') &&
    trimmed.split(/\r?\n/).filter(Boolean).length === 1 &&
    trimmed.length <= 200
  ) {
    return 'screenshot'
  }
  if (!trimmed && !html.trim()) return 'screenshot'
  return 'image'
}

/** Recover the original filename of a copied web/file image, when advertised. */
export function extractClipboardImageFileName(text: string, html: string): string | undefined {
  for (const src of [html, text]) {
    const fromUrl = localPathFromClipboardFileUrl(src)
    if (fromUrl) {
      const base = fromUrl.replace(/^.*[\\/]/, '')
      if (base) return base
    }
  }
  const http = text.match(/^(https?:\/\/.+)\/([^/?#]+)$/i)
  if (http && /\.(png|jpe?g|gif|webp|bmp|svg|avif)$/i.test(http[2])) {
    try {
      return decodeURIComponent(http[2])
    } catch {
      return http[2]
    }
  }
  return undefined
}

/** `Screenshot 2026-08-31 14.05.09.png` — Windows-style screenshot naming. */
export function formatScreenshotName(date = new Date(), ext = 'png'): string {
  const p = (n: number): string => String(n).padStart(2, '0')
  const stamp = `${date.getFullYear()}-${p(date.getMonth() + 1)}-${p(date.getDate())} ${p(date.getHours())}.${p(date.getMinutes())}.${p(date.getSeconds())}`
  return `Screenshot ${stamp}.${ext.replace(/^\./, '') || 'png'}`
}

function capturedNameFor(source: ImageSource, fileName: string | undefined, when: Date): string | null {
  if (fileName) return fileName
  if (source === 'screenshot') return formatScreenshotName(when)
  return null
}

/* ---------------------------------------------------------------- */
/* File payloads                                                     */
/* ---------------------------------------------------------------- */

/** Build a `FilePayload` from an absolute path (best-effort stat). */
export function buildFilePayload(path: string): FilePayload {
  let byteSize: number | null = null
  let isDirectory = false
  try {
    const st = statSync(path)
    byteSize = st.size
    isDirectory = st.isDirectory()
  } catch {
    /* path removed / on a disconnected drive — size stays null */
  }
  const name = basename(path)
  const extension = isDirectory ? '' : extname(path).slice(1).toLowerCase()
  return { kind: 'file', path, name, extension, byteSize, isDirectory }
}

/** One `file` for a single path, a `stack` of `file`s for several. */
export function filesToItemData(paths: string[]): ItemData {
  const payloads = paths.map(buildFilePayload)
  return payloads.length === 1 ? payloads[0] : { kind: 'stack', members: payloads }
}

/* ---------------------------------------------------------------- */
/* Tabular write-back formatting                                     */
/* ---------------------------------------------------------------- */

/**
 * Normalize text+HTML for writing back to the clipboard so spreadsheet apps
 * keep the grid: line breaks -> CRLF (Excel treats bare LF as an in-cell
 * Alt+Enter), and tab-separated text with no real <table> gets a synthesized
 * standard table.
 */
export function formatTabularDataForClipboard(text: string, rawHtml?: string): { text: string; html?: string } {
  if (!text) return { text: '', html: rawHtml }
  const crlfText = text.replace(/\r?\n/g, '\r\n')

  if (text.includes('\t')) {
    if (rawHtml && /<table\b[^>]*>/i.test(rawHtml)) return { text: crlfText, html: rawHtml }
    const htmlRows = text
      .split(/\r?\n/)
      .map((row) => {
        const cells = row
          .split('\t')
          .map((cell) => {
            const escaped = cell
              .replace(/&/g, '&amp;')
              .replace(/</g, '&lt;')
              .replace(/>/g, '&gt;')
              .replace(/"/g, '&quot;')
              .replace(/'/g, '&#39;')
            return `<td>${escaped}</td>`
          })
          .join('')
        return `<tr>${cells}</tr>`
      })
      .join('')
    return { text: crlfText, html: `<table border="0" cellpadding="0" cellspacing="0"><tbody>${htmlRows}</tbody></table>` }
  }
  return { text: crlfText, html: rawHtml }
}

/* ---------------------------------------------------------------- */
/* Snapshot -> ItemData (pure)                                       */
/* ---------------------------------------------------------------- */

function makeTextPayload(text: string, html: string | null): TextPayload {
  // `preview` carries the FULL text out of `formats`; ItemStore.add() truncates
  // it to PREVIEW_LIMIT and spills the remainder to a payload file.
  return { kind: 'text', preview: text, truncated: text.length > PREVIEW_LIMIT, charCount: text.length, html }
}

function makeImagePayload(snap: ClipSnapshot, trimmedText: string, trimmedHtml: string): ImagePayload {
  const source = detectClipboardImageSource(snap.types, trimmedText, trimmedHtml)
  const fileName = extractClipboardImageFileName(trimmedText, trimmedHtml)
  // imageId + byteSize are filled by the watcher once the PNG is staged.
  return {
    kind: 'image',
    imageId: '',
    width: snap.image?.width ?? 0,
    height: snap.image?.height ?? 0,
    byteSize: snap.image?.png.length ?? 0,
    capturedName: capturedNameFor(source, fileName, new Date())
  }
}

/**
 * Classify a snapshot (+ already-read file paths) into one `ItemData`, or null.
 * Priority: files > image-intent > text (URL -> link). Pure and synchronous.
 */
export function analyzeSnapshot(snap: ClipSnapshot, files: string[]): ItemData | null {
  if (isExcludedByTypes(snap.types)) return null
  if (files.length) return filesToItemData(files)

  const hasImage = !!snap.image
  const rawText = snap.text
  const rawHtml = snap.html ?? ''
  const trimmedText = rawText.trim()
  const trimmedHtml = rawHtml.trim()

  const localFile = localPathFromClipboardFileUrl(trimmedHtml) || localPathFromClipboardFileUrl(trimmedText)
  if (localFile) return buildFilePayload(localFile)

  if (hasImage && isScreenshotOrImageIntent(hasImage, trimmedText, trimmedHtml, snap.types)) {
    return makeImagePayload(snap, trimmedText, trimmedHtml)
  }

  if (trimmedText) {
    if (isUrlText(trimmedText)) {
      const link: LinkPayload = { kind: 'link', url: trimmedText, title: null }
      return link
    }
    const textToStore = rawText.includes('\t') ? rawText.replace(/\r?\n+$/, '') : trimmedText
    const html = trimmedHtml && trimmedHtml !== trimmedText ? rawHtml : null
    return makeTextPayload(textToStore, html)
  }

  if (hasImage) return makeImagePayload(snap, trimmedText, trimmedHtml)
  return null
}

/** FNV-1a over ~400 evenly-spaced bytes — cheap, stable, collision-safe. */
function hashBytes(bytes: Buffer): string {
  const step = Math.max(1, Math.floor(bytes.length / 400))
  let hash = 0x811c9dc5
  for (let i = 0; i < bytes.length; i += step) {
    hash ^= bytes[i]
    hash = Math.imul(hash, 0x01000193) >>> 0
  }
  return hash.toString(36)
}

/**
 * A cheap signature used to detect the clipboard *changed*. On Windows a
 * `seq:<n>:` prefix from the OS sequence number makes even a re-copy of
 * identical content look new (so a repeated Ctrl+C bumps hitCount); elsewhere
 * the prefix is absent and change detection is content-based. Pure.
 */
export function signatureForSnapshot(snap: ClipSnapshot, seq: number, files: string[]): string {
  const seqPrefix = seq > 0 ? `seq:${seq}:` : ''
  if (isExcludedByTypes(snap.types)) return `${seqPrefix}excluded`
  if (files.length) return `${seqPrefix}files:${files.join('\n')}`

  const hasImage = !!snap.image
  const trimmedText = snap.text.trim()
  const trimmedHtml = (snap.html ?? '').trim()

  if (hasImage && isScreenshotOrImageIntent(hasImage, trimmedText, trimmedHtml, snap.types) && snap.image) {
    return `${seqPrefix}image:${snap.image.width}x${snap.image.height}:${hashBytes(snap.image.png)}`
  }
  if (trimmedText) return `${seqPrefix}text:${trimmedText}`
  if (hasImage && snap.image) {
    return `${seqPrefix}image:${snap.image.width}x${snap.image.height}:${hashBytes(snap.image.png)}`
  }
  return `${seqPrefix}empty`
}

/* ---------------------------------------------------------------- */
/* Async wrappers (glue the live clipboard to the pure functions)    */
/* ---------------------------------------------------------------- */

async function readFiles(snap: ClipSnapshot): Promise<string[]> {
  let files = reader.parseFiles(snap.raw, snap.text)
  // Windows: the synchronous CF_HDROP is gone, so fall back to a PowerShell
  // GetFileDropList() when the types hint a file copy and no image is present.
  if (!files.length && 'readFilesRich' in reader && reader.hasFileHint(snap.types) && !snap.image) {
    files = await reader.readFilesRich()
  }
  return files
}

/**
 * Snapshot the clipboard into one `ItemData`. For image captures the staged PNG
 * bytes come back too, so the watcher persists them without a second read.
 */
export async function captureClipboard(): Promise<{ data: ItemData; imagePng?: Buffer } | null> {
  const snap = await readSnapshot(reader.fileFormats)
  const files = await readFiles(snap)
  const data = analyzeSnapshot(snap, files)
  if (!data) return null
  if (data.kind === 'image' && snap.image) return { data, imagePng: snap.image.png }
  return { data }
}

/** Async change-detection signature (see `signatureForSnapshot`). */
export async function clipboardSignature(): Promise<string> {
  const snap = await readSnapshot(reader.fileFormats)
  const files = await readFiles(snap)
  return signatureForSnapshot(snap, reader.clipboardSequenceNumber(), files)
}
